var fs = require('fs'),
    request = require('request');

var download = function(uri, filename, callback){
  request.head(uri, function(err, res, body){
    console.log('content-type:', res.headers['content-type']);
    console.log('content-length:', res.headers['content-length']);
    request(uri).pipe(fs.createWriteStream(filename)).on('close', callback);
  });
};

const categories = [
    { id: 1, title: 'Arts and entertainment' },
    { id: 102, title: 'Architecture' },
    { id: 103, title: 'Arts and antiques' },
    { id: 105, title: 'Celebrities and gossip' },
    { id: 110, title: 'Literature' },
    { id: 111, title: 'Movies' },
    { id: 112, title: 'Music' },
    { id: 114, title: 'Television' },
    { id: 116, title: 'Theatre and dance' },
    { id: 2, title: 'Business' },
    { id: 202, title: 'Agriculture' },
    { id: 204, title: 'Biotech' },
    { id: 205, title: 'Construction' },
    { id: 207, title: 'Government' },
    { id: 208, title: 'Human resources' },
    { id: 209, title: 'Logistics' },
    { id: 210, title: 'Marketing' },
    { id: 3, title: 'Education' },
    { id: 301, title: 'Adult education' },
    { id: 302, title: 'Careers' },
    { id: 303, title: 'College' },
    { id: 304, title: 'Kids education' },
    { id: 4, title: 'Family and parenting' },
    { id: 403, title: 'Parenting kids' },
    { id: 404, title: 'Parenting teens' },
    { id: 405, title: 'Pregnancy' },
    { id: 5, title: 'Food and drink' },
    { id: 501, title: 'Cocktails beer' },
    { id: 502, title: 'Coffee tea' },
    { id: 503, title: 'Desserts and baking' },
    { id: 504, title: 'Food' },
    { id: 505, title: 'Vegetarian' },
    { id: 506, title: 'Wine' },
    { id: 6, title: 'Health and fitness' },
    { id: 601, title: 'Diet and nutrition' },
    { id: 602, title: 'Fitness' },
    { id: 603, title: 'Health and medicine' },
    { id: 7, title: 'Hobbies' },
    { id: 703, title: 'Cards and gambling' },
    { id: 704, title: 'Comic books' },
    { id: 705, title: 'Computer games' },
    { id: 706, title: 'Drawing and painting' },
    { id: 708, title: 'Leisure activities' },
    { id: 709, title: 'Needlework' },
    { id: 711, title: 'Paranormal phenomena' },
    { id: 712, title: 'Photography' },
    { id: 8, title: 'Home and garden' },
    { id: 801, title: 'Home decorating' },
    { id: 802, title: 'Home repair' },
    { id: 803, title: 'Garden' },
    { id: 10, title: 'Pets' },
    { id: 1001, title: 'Birds' },
    { id: 1002, title: 'Dogs and cats' },
    { id: 1004, title: 'Fish and marine life' },
    { id: 1006, title: 'Other animals' },
    { id: 11, title: 'Religion and spirituality' },
    { id: 1102, title: 'Atheism agnosticism' },
    { id: 1103, title: 'Buddhism' },
    { id: 1104, title: 'Catholicism' },
    { id: 1105, title: 'Christianity' },
    { id: 1106, title: 'Hinduism' },
    { id: 1107, title: 'Islam' },
    { id: 1108, title: 'Judaism' },
    { id: 1109, title: 'Pagan wiccan' },
    { id: 12, title: 'Science' },
    { id: 1201, title: 'Astronomy' },
    { id: 1202, title: 'Biology' },
    { id: 1205, title: 'Chemistry' },
    { id: 1207, title: 'History' },
    { id: 1208, title: 'Math' },
    { id: 1209, title: 'Other sciences' },
    { id: 1211, title: 'Physics' },
    { id: 14, title: 'Society' },
    { id: 1401, title: 'Dating' },
    { id: 1403, title: 'Gay life' },
    { id: 1407, title: 'Senior living' },
    { id: 15, title: 'Sports' },
    { id: 1501, title: 'Auto racing' },
    { id: 1502, title: 'Baseball' },
    { id: 1503, title: 'Basketball' },
    { id: 1504, title: 'Fishing' },
    { id: 1505, title: 'Football' },
    { id: 1506, title: 'Golf' },
    { id: 1507, title: 'Martial arts' },
    { id: 1508, title: 'Running' },
    { id: 1510, title: 'Soccer' },
    { id: 1511, title: 'Surfing' },
    { id: 1512, title: 'Tennis' },
    { id: 1513, title: 'Winter sports' },
    { id: 16, title: 'Style and fashion' },
    { id: 1601, title: 'Cosmetics' },
    { id: 1602, title: 'Jewelry' },
    { id: 1603, title: 'Life style' },
    { id: 1604, title: 'Mens fashion' },
    { id: 1605, title: 'Tattoos and piercings' },
    { id: 1606, title: 'Weddings' },
    { id: 1607, title: 'Womens fashion' },
    { id: 17, title: 'Technology and computing' },
    { id: 1701, title: 'Audio and video' },
    { id: 1702, title: 'Computers' },
    { id: 1704, title: 'Electronics' },
    { id: 1707, title: 'Programming' },
    { id: 18, title: 'Travel' },
    { id: 1801, title: 'Adventure travel' },
    { id: 1804, title: 'Travel and tourism' },
    { id: 19, title: 'Vehicles' },
    { id: 1901, title: 'Airplanes' },
    { id: 1902, title: 'Bicycles' },
    { id: 1903, title: 'Boats' },
    { id: 1904, title: 'Cars' },
    { id: 1905, title: 'Motorcycles' },
    { id: 1907, title: 'Trains' },
    { id: 1908, title: 'Trucks' },
];

categories.forEach(category => {
    const title = category.title.replace(/ /g, '+');
    const url = `https://dummyimage.com/400x400/f26f61/ffffff&text=${title}`;
    console.log(url);
    download(url, `client/assets/${category.id}.png`, function() {
      console.log('done');
    });
});
